# This workflow will build an Arch Linux ISO file with the commit on it
name: repo-add
on:
  push:
    paths: "**/*.tar.zst"
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v3
      - name: Install Packages via Pacman
        run: pacman -Sy; pacman --noconfirm -S git python python-pip base-devel
      - name: repo-add
        run: bash ./repoadd.sh ppr
      - name: push
        run: |
          git add -A
          git commit -S -m "gh-action: Update ppr.db" || echo "nothing"
          
